### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by tcccorp** [kartben/artificial-nose#14]
hello, when I try to build the app  there is an error 'FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable'  and it seems trouble is with the line below

platform_packages = 
	framework-arduino-samd-seeed@https://github.com/Seeed-Studio/ArduinoCore-samd.git

if I remove framework-arduino-samd-seeed@, it is a little bit better until another trouble :(  : 

> Executing task: C:\Users\Serge\.platformio\penv\Scripts\platformio.exe run --target upload <

Processing seeed_wio_terminal (platform: atmelsam; board: seeed_wio_terminal; framework: arduino)
----------------------------------------------------------------------------------Tool Manager: Installing platformio/tool-bossac @ ~1.10900.0
Tool Manager: tool-bossac @ 1.10900.0 has been installed!
Tool Manager: Installing ArduinoCore-samd @ *
**Error: Could not find the package with 'ArduinoCore-samd @ *' requirements for your system 'windows_amd64'**
The terminal process "C:\Users\Serge\.platformio\penv\Scripts\platformio.exe 'run', '--target', 'upload'" terminated with exit code: 1.

thanks 

Serge

**Comment by kartben** [comment]
Bonsoir Serge!

This is weird. I am assuming you're using the latest version of Platform.io? Are you using it standalone or from VS Code? It should really matter but just trying to see what could cause issue on your machine...

**Comment by tcccorp** [comment]
Bonsoir  Benjamin , thanks for your reply :)

I use  VS 1.58.2  and Platform.io (Core 5.1.1·Home 3.3.4)

I ll debug this week end and I ll keep you informed 

Serge

**Comment by tcccorp** [comment]
Hello Sébastien, 

so I tried several times on Windows and it still fails... So I tested on Kali ( trouble with python)  and Ubuntu.... 

I made a fresh install on Ubuntu and it worked after a little modification : I added upload_port = /dev/ttyACM1 in the platformio.ini because in automatic mode I bricked the terminal when I uploaded the soft

so now I have to continue :)  I'll be happy to see my bread 

have a nice day 

Serge
