### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by NAMost** [kartben/artificial-nose#24]
Hi, 
I have compilation error with master branch.
This is the log file.
[log_error.txt](https://github.com/kartben/artificial-nose/files/11290704/log_error.txt)

![image](https://user-images.githubusercontent.com/23708984/233495986-80bd6d30-acb5-4993-af7e-07c8f4e53927.png)

thanks,
Mustapha

**Comment by kartben** [comment]
should be fixed now! Culprit was one of the few Arduino libraries for which I hadn't pinned a specific version.

**Comment by munakbi** [comment]
it works fine now.
thanks kartben

**Comment by Musauce** [comment]
It works now!!!! 
You are professional!

**Comment by kartben** [comment]
> It works now!!!! 
> You are professional!

Ahah :) please keep me posted about what you're up to (if you want to!) and don't hesitate to open other issues of you find other problems.

**Comment by Musauce** [comment]
> > It works now!!!!
> > You are professional!
> 
> Ahah :) please keep me posted about what you're up to (if you want to!) and don't hesitate to open other issues of you find other problems.

I'm working on an intelligent nose which can recognize different types of liquid by 'smelling'. And I found this issue when I tried to compile the Wio Terminal. Thank you for your solution, it is solved now!
